name: Github Actions Demo
on: [push] # 何时触发, 这里设置 push 时触发
jobs: 
  Check-Github-Actions:
    runs-on: ubuntu-latest
    steps: 
      - run: echo 'triggered by a ${{ github.event_name }} event'
      - run: echo 'running on a ${{ runner.os }} server hosted by server'
      - name: check out repo code
        uses: actions/checkout@v2
      - run: echo 'the ${{ github.repository }} has been cloned'
      - name: List files in the repo
        run: | 
          ls ${{ github.workspace }}
